name: tf-gpu
channels:
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=3.3.1=pyhd3eb1b0_0
  - ca-certificates=2021.7.5=haa95532_1
  - certifi=2021.5.30=py39haa95532_0
  - cffi=1.14.6=py39h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py39haa95532_0
  - importlib-metadata=3.10.0=py39haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - ipykernel=5.3.4=py39h7b7c402_0
  - ipython=7.22.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39haa95532_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - libsodium=1.0.18=h62dcd97_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39h2bbff1b_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py39haa95532_0
  - openssl=1.1.1k=h2bbff1b_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.7.0=py_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=21.1.3=py39haa95532_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - pycparser=2.20=py_2
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py39h2bbff1b_0
  - python=3.9.6=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pywin32=228=py39hbaba5e8_1
  - pywinpty=0.5.7=py39haa95532_0
  - pyzmq=20.0.0=py39hd77b12b_1
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39haa95532_0
  - sqlite=3.36.0=h2bbff1b_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tornado=6.1=py39h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - tzdata=2021a=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - zeromq=4.3.3=ha925a31_3
  - zipp=3.5.0=pyhd3eb1b0_0
  - pip:
    - absl-py==0.13.0
    - astunparse==1.6.3
    - cachetools==4.2.2
    - charset-normalizer==2.0.4
    - cycler==0.10.0
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.34.0
    - google-auth-oauthlib==0.4.5
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==3.2
    - keras==2.8.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - libclang==13.0.0
    - markdown==3.3.4
    - matplotlib==3.4.2
    - numpy==1.22.2
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pandas==1.3.1
    - pillow==8.3.1
    - protobuf==3.17.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytz==2021.1
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.8.0
    - six==1.15.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.8.0
    - tensorflow-estimator==2.5.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - tf-estimator-nightly==2.8.0.dev2021122109
    - typing-extensions==3.7.4.3
    - urllib3==1.26.6
    - werkzeug==2.0.1
    - wrapt==1.12.1
prefix: C:\Users\thikj\anaconda3\envs\tf-gpu
